[workspace]
members = [
    "contracts/auth-onsocial",
    "contracts/ft-wrapper-onsocial",
    "contracts/relayer-onsocial",
    "tests",
]
resolver = "2"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
panic = "abort"
overflow-checks = true
debug = false

[profile.test]
opt-level = 0
debug = true