version: '3.9'
services:
  near-sandbox:
    image: nearprotocol/near-sandbox:1.40.0
    ports:
      - "3030:3030"
    restart: unless-stopped
    environment:
      - NEAR_SANDBOX_PORT=3030
    volumes:
      - near-data:/root/.near
    command: --fast

  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.builder
    volumes:
      - ..:/code
      - cargo-cache:/root/.cargo
      - target-cache:/code/target
    working_dir: /code
    command: bash -c "chmod +x scripts/build.sh && ./scripts/build.sh"
    environment:
      - RUSTUP_HOME=/root/.rustup
      - CARGO_HOME=/root/.cargo
      - NEAR_ENV=sandbox
      - NEAR_NODE_URL=http://near-sandbox:3030

volumes:
  near-data:
  cargo-cache:
  target-cache: