[package]
name = "relayer-onsocial"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/OnSocial-Labs/onsocial-contracts"

[package.metadata.near.reproducible_build]
rust_version = "1.86.0"
cargo_near_version = "0.14.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.12.0"
near-crypto = "0.30.1"
ed25519-dalek = "2.1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "1.5.7"
near-sdk-macros = "5.12.0"
getrandom = { version = "0.2.16", features = ["js"] }
hex = "0.4.3"
base64 = "0.22.1"

[dev-dependencies]
near-sdk = { version = "5.12.0", features = ["unit-testing"] }
near-crypto = "0.30.1"
cargo-near = "0.14.1"
