name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        contract: [auth-onsocial, ft-wrapper-onsocial, relayer-onsocial, all]
    steps:
      - uses: actions/checkout@v4
      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Build Docker image
        run: make build-docker
      - name: Start NEAR Sandbox
        run: |
          make start-sandbox
          for i in {1..30}; do
            if curl -s http://localhost:3030/status > /dev/null; then
              echo "Sandbox is ready"
              break
            fi
            echo "Waiting for sandbox..."
            sleep 2
          done
          curl -s http://localhost:3030/status || exit 1
      - name: Build contracts
        run: make build
      - name: Generate ABIs
        run: make abi
      - name: Run tests
        run: |
          if [ "${{ matrix.contract }}" == "all" ]; then
            make test
            make test-integration
          else
            make test-unit CONTRACT=${{ matrix.contract }}
            make test-integration CONTRACT=${{ matrix.contract }}
          fi
      - name: Generate test coverage
        run: make test-coverage CONTRACT=${{ matrix.contract }}
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.contract }}
          path: coverage/
      - name: Cache artifacts
        uses: actions/cache@v4
        with:
          path: |
            target/
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Clean up sandbox
        if: always()
        run: make clean-sandbox